<?php echo datatables(); ?><?php echo jquery_autocomplete(); ?><link rel="stylesheet" href="<?php echo base_url(); ?>css/print.css" type="text/css" media="print" id="css_print" /><style type="text/css" media="screen">
	.search-box {		padding-top: 5px;	}	.search-box input[type=text] {		border: 1px solid white !important;	}
</style><script type='text/javascript'>	
	$().ready(function () {								// Autocomplete barang		$('#barang').autocomplete('<?php echo $this->page->base_url('autocomplete') ?>');				$('#barang').result(function(event, data, format){			$(this).val(data[0]);			$('#id_barang').val(data[1]);			$('#harga').val('Rp. '+Library.currency(data[2]));		});				// Tambah data		$('#beli').click(function (e) {			e.preventDefault();			var valid = $('form').validationEngine('validate');						if (valid == true) {							var no		= 1;				var nama 	= $('#barang').val();				var qty		= $('#qty').val() * 1;				var harga	= $('#harga').val().split('Rp. ').join('').split('.').join('') * 1;			 	var sub 	= qty * harga;				var currNum = $('#tabel tbody tr:eq(-1) td:eq(0)').html().split('.').join('');	        	var pr      = $('#tabel tbody td:contains("'+ nama +'")').parents('tr')[0];	        	var currQty = $('#tabel tbody td:contains("'+ nama +'")').parent().find('td:eq(3)').text();				var item    = $('#tabel tbody td:contains("'+ nama +'")').text();				var index 	= $('#tabel tbody tr:contains("'+ nama +'")').index();								if (currNum > 0) {		    		no = no + currNum * 1;			   	}			   				   	// Update qty dan subtotal jika nama sama			   	if (nama == item) {					var addQty = parseInt(currQty) + parseInt(qty);		            var addSub = (addQty * harga);		            	             	oTable.fnUpdate(addQty, pr, 3, false);	             	oTable.fnUpdate('Rp. '+Library.currency(addSub), pr, 4, false);	             	oTable.fnDraw();		            // oTable.row(index).data([		            	// currNum+'.',		            	// item,		            	// 'Rp. '+Library.currency(harga),		            	// addQty,		            	// 'Rp. '+Library.currency(addSub),		            	// '<a href="#" class="hapus">Hapus <i class="fa fa-times"></i></a>',		            	// $('#id_barang').val(),	            	// ]).draw();			   	} else {					oTable.fnAddData([		                no+'.',		                nama,		                'Rp. '+Library.currency(harga),		                qty,		                'Rp. '+Library.currency(sub),		                '<a href="#" class="hapus">Hapus <i class="fa fa-times"></i></a>',		                $('#id_barang').val(),		            ]);			   	}			   				   	$('form input').not('#pengguna').val('');			   	$('#barang').focus();		   	} else {		   		$("form").validationEngine({"showOneMessage":true, "binded":false});		   	}		});				// Initiate table
		var oTable = $('#tabel').DataTable({		 	"bFilter": false,		 	"bPaginate": false,		 	"bInfo": false,		 	"bSort": false,		 	"bLengthChange": false,		 	"fnFooterCallback": function ( nRow, aaData, iStart, iEnd, aiDisplay ) {	            /*	             * Calculate the total market share for all browsers in this table (ie inc. outside	             * the pagination)	             */	            var qtyTot = 0;	            var subTot = 0;	            for ( var i = 0 ; i < aaData.length ; i++ )	            {	                // Parsing harga menjadi integer	                prs     = aaData[i][4].split('Rp. ').join('').split('.').join('');	                subTot += prs*1;		                qtyTot += aaData[i][3]*1;	            }		            /* Modify the footer row to match what we want */	            var nCells = nRow.getElementsByTagName('th');	            nCells[1].innerHTML = qtyTot;	            nCells[2].innerHTML = 'Rp. '+Library.currency(subTot);	        },	        "fnRowCallback": function ( row, data, index ) {	        	// Kolom nomor	        	$('td', row).eq(0).addClass('text-center');	        	// Kolom harga	            $('td', row).eq(2).addClass('text-right');	            // Kolom jumlah	            $('td', row).eq(3).addClass('text-center');	            // Kolom subtotal	            $('td', row).eq(4).addClass('text-right');	            // Kolom aksi	            $('td', row).eq(5).addClass('text-center');	        }		 });		 		 // Hapus data		 $('#tabel tbody').on('click', 'a.hapus', function (e) {		 	e.preventDefault();		 			 	var nRow = $(this).parents('tr')[0];        	oTable.fnDeleteRow(nRow);		 	// oTable.row($(this).parents('tr')).remove().draw();		 });		 		 // Simpan data		 $('#simpan').click(function () {		 	var data 		= oTable.fnGetData();		 	var totalQty    = $('#tabel tfoot th:eq(1)').html();        	var total       = $('#tabel tfoot th:eq(2)').html();        	var no_nota		= '<?php echo $nomor; ?>';        	        	$.ajax({
				url: '<?php echo site_url('transaksi/penjualan/simpan'); ?>',
				data: {data:data, qty:totalQty, total:total, no:no_nota},
				type: 'post',
				dataType: 'json',
				success: function (result) {					window.location = result.trans;					window.open(result.pdf);
				}
			});		 });
	});
</script><h1>Form Penjualan</h1> <h2 class="right">No. Nota - <?php echo $nomor; ?></h2><div class="clear"></div><div class="actions">	<form>		<input type="text" name="barang" placeholder="Nama Barang" id="barang" class="validate[required]" />		<input type="text" name="harga" placeholder="Harga" id="harga" class="validate[required]" />		<input type="text" name="qty" placeholder="Jumlah" id="qty" class="validate[required]" />		<button class="btn btn-success" id="beli">Beli</button>		<input type="hidden" name="id_barang" id="id_barang"/>		<input type="hidden" name="no_nota" id="no_nota" value="<?php echo $nomor; ?>" />			<div class="search-box">			Pegawai: <input type="text" name="pengguna" value="<?php echo $this->session->userdata('nama'); ?>" id="pengguna" readonly />
		</div>
	</form>
</div><div class="right"><button class="btn btn-primary" id="simpan">Simpan</button></div><br /><br /><table id="tabel" class="stripe hover row-border cell-border">
	<thead>		<tr>			<th width="20px">No.</th>			<th>Barang</th>			<th>Harga</th>			<th>Jumlah</th>			<th>Subtotal</th>			<th>Aksi</th>		</tr>	</thead>	<tbody>	</tbody>	<tfoot>		<tr>			<th colspan="3">Total</th>			<th></th>			<th align="right"></th>			<th></th>		</tr>	</tfoot>
</table>